default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 6732

development:
  <<: *default
  database: blog-basic-cb_development
  username: postgres
  password: 6732

test:
  <<: *default
  database: blog-basic-cb_test

production:
  <<: *default
  database: blog-basic-cb_production
  username: blog-basic-cb
  password: 6732